name: cie_team1
description: dev-team-1-cie-app-in-flutter 

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: "^1.0.1"
  path_provider: "^0.4.0"
  cupertino_icons: ^0.1.0
  url_launcher: "^3.0.1"
  connectivity: "^0.3.1"
  flutter_html_view: "^0.3.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: "^0.3.2"
  progress_hud: "^0.2.2"

flutter_icons:
  image_path: "res/images/hm_app_icon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - res/images/hm_logo.png
    - res/images/karlstrasse.png
    - res/images/lothstrasse.png
    - res/images/pasing.png
